apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbprocessor
  template:
    metadata:
      labels:
        app: sbprocessor
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      volumes:
      - name: config
        configMap:
          name: sbprocessor-config
      containers:
      - name: sbmessageprocessor
        image: myaksalacontainerregistry.azurecr.io/sbmessageprocessor:v1
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: "/app/config/config.py"
          subPath: config.py
          readOnly: true
        env:
        - name: CONNECTION_STR
          valueFrom:
            secretKeyRef:
              name: sb-conn-string
              key: CONNECTION_STR
        - name: KEDA_SERVICEBUS_QUEUE_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: sb-conn-string
              key: CONNECTION_STR
        resources:
          limits:
            memory: 800Mi
            cpu: 1
          requests:
            memory: 600Mi
            cpu: 600m
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sbprocessor-config
data:
  config.py: |
    max_wait_time=15
    TOPIC_NAME = "mytopic"
    SUBSCRIPTION_NAME = "s1"