apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbprocessor
  template:
    metadata:
      labels:
        app: sbprocessor
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: sbmessageprocessor
        image: myaksalacontainerregistry.azurecr.io/sbmessageprocessor:v1
        env:
        - name: KEDA_SERVICEBUS_QUEUE_CONNECTIONSTRING
          value: Endpoint=sb://myaks-sb-27.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=kYY8m4mULTEAO4hzEeFMinx5zpXPPM+g+U1V/0Ck2fA=
        resources:
          limits:
            memory: 800Mi
            cpu: 1
          requests:
            memory: 600Mi
            cpu: 600m